# Generated by Django 3.1.7 on 2021-03-29 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, 'Super admin'), (2, 'Admin'), (3, 'Donator'), (4, 'Needy')])),
                ('verified_needy', models.BooleanField(null=True)),
                ('first_name', models.CharField(blank=True, max_length=127)),
                ('last_name', models.CharField(blank=True, max_length=127)),
                ('melli_code', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(blank=True, max_length=127)),
                ('mobile_number', models.CharField(max_length=31)),
                ('verified_email', models.BooleanField(default=False)),
                ('verified_mobile', models.BooleanField(default=False)),
                ('house_phone', models.CharField(blank=True, max_length=31)),
                ('workplace_phone', models.CharField(blank=True, max_length=31)),
                ('gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')])),
                ('married', models.BooleanField(blank=True, choices=[(1, 'married'), (0, 'not married')])),
                ('birth_date', models.DateField(blank=True)),
                ('signup_date', models.DateTimeField(auto_now=True)),
                ('creator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='The one who signed the user up for the first time.+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
