# Generated by Django 3.1.7 on 2021-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
