# Generated by Django 3.1.7 on 2021-04-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_auto_20210412_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='married',
            field=models.BooleanField(blank=True, choices=[(1, 'married'), (0, 'not married')], default=0),
        ),
    ]
