# Generated by Django 3.1.7 on 2021-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_auto_20210412_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
