# Generated by Django 3.1.7 on 2021-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_userprofile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='married',
            field=models.BooleanField(blank=True, choices=[(0, 'not married'), (1, 'married')], default=0),
        ),
    ]
