# Generated by Django 3.1.7 on 2021-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_auto_20210417_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='house_phone',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workplace_phone',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
