# Generated by Django 3.1.7 on 2021-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_auto_20210417_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_pass_token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
