# Generated by Django 3.1.7 on 2021-04-22 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0014_userprofile_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'no feedback'), (1, 'accepted'), (-1, 'failed')], default=0)),
                ('feedback', models.TextField(default='', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
