# Generated by Django 3.1.7 on 2021-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0023_auto_20210504_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verified_needy',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
