# Generated by Django 3.1.7 on 2021-05-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0028_auto_20210516_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatesin',
            name='transferee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transferee', to='App1.userprofile'),
        ),
    ]
