# Generated by Django 3.1.7 on 2021-05-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0029_auto_20210516_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'no feedback'), (1, 'accepted'), (-1, 'failed')], default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='needy', to='App1.userprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App1.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DonatesOut',
        ),
    ]
