# Generated by Django 3.1.7 on 2021-05-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0030_auto_20210523_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needrequest',
            name='product',
        ),
        migrations.AlterField(
            model_name='needrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'accepted'), (-1, 'failed')], default=0),
        ),
    ]
