# Generated by Django 3.1.7 on 2021-05-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0031_auto_20210524_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='donatorOrNeedy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App1.userprofile'),
        ),
    ]
