# Generated by Django 3.1.7 on 2021-05-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0032_auto_20210524_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatesin',
            name='donator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donator', to='App1.userprofile'),
        ),
    ]
