# Generated by Django 3.1.7 on 2021-05-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0034_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, default='127.0.0.1:8000/images/default.png', max_length=512, null=True),
        ),
    ]
