# Generated by Django 3.1.7 on 2021-05-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0037_auto_20210531_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
