# Generated by Django 3.1.7 on 2021-06-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0038_auto_20210601_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
