# Generated by Django 3.1.7 on 2021-06-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0039_auto_20210601_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
