# Generated by Django 3.1.7 on 2021-06-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0041_auto_20210606_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatesin',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
