# Generated by Django 3.1.7 on 2021-06-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0042_auto_20210606_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=128, null=True)),
            ],
        ),
    ]
