# Generated by Django 3.1.7 on 2021-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0043_expiredtokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
