# Generated by Django 3.1.7 on 2021-06-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0044_auto_20210608_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
