# Generated by Django 3.1.7 on 2021-06-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0045_auto_20210608_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='create_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
