# Generated by Django 3.1.7 on 2021-06-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0046_transactions_create_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, default='/images/default.png', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.CharField(blank=True, default='/images/default_profile.png', max_length=512, null=True),
        ),
    ]
