# Generated by Django 3.1.7 on 2021-06-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0047_auto_20210616_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
